---
- name: Include setup tasks
  ansible.builtin.import_tasks: setup.yml

- name: Include deployment tasks
  ansible.builtin.import_tasks: deploy.yml

- name: Include service tasks
  ansible.builtin.import_tasks: service.yml


